language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t luke0619s/react-test -f ./client/Dockerfile.dev ./client # 根據Dockerfile.dev建造image 並以./client作為context

script:
  - docker run -e CI=true luke0619s/react-test npm test

# 替AWS的EB建置image
after_success:
  - docker build -t luke0619s/multi-client ./client
  - docker build -t luke0619s/multi-nginx ./nginx
  - docker build -t luke0619s/multi-server ./server
  - docker build -t luke0619s/multi-worker ./worker
  # Log in to the docker CLI -> docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push luke0619s/multi-client
  - docker push luke0619s/multi-nginx
  - docker push luke0619s/multi-server
  - docker push luke0619s/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-458271370291'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY